// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using One_P7.ThreeLayer.Database.SQLiteAdventureWorks.Models;
using System;
using System.Collections.Generic;

namespace One_P7.ThreeLayer.Database.SQLiteAdventureWorks.Models.Configurations
{
    public partial class BuildVersionConfiguration : IEntityTypeConfiguration<BuildVersion>
    {
        public void Configure(EntityTypeBuilder<BuildVersion> entity)
        {
            entity.HasKey(e => e.SystemInformationId);

            entity.ToTable("BuildVersion");

            entity.Property(e => e.SystemInformationId).HasColumnName("SystemInformationID");
            entity.Property(e => e.DatabaseVersion)
                .IsRequired()
                .HasColumnName("Database Version");
            entity.Property(e => e.ModifiedDate)
                .HasDefaultValueSql("datetime('now')")
                .HasColumnType("DATETIME");
            entity.Property(e => e.VersionDate).HasColumnType("DATETIME");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BuildVersion> entity);
    }
}
