// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using One_P7.ThreeLayer.Database.SQLiteAdventureWorks.Models;
using System;
using System.Collections.Generic;

namespace One_P7.ThreeLayer.Database.SQLiteAdventureWorks.Models.Configurations
{
    public partial class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> entity)
        {
            entity.ToTable("Product");

            entity.HasIndex(e => e.Name, "IX_Product_Name").IsUnique();

            entity.HasIndex(e => e.ProductNumber, "IX_Product_ProductNumber").IsUnique();

            entity.HasIndex(e => e.Rowguid, "IX_Product_rowguid").IsUnique();

            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.DiscontinuedDate).HasColumnType("DATETIME");
            entity.Property(e => e.ListPrice).HasColumnType("INTEGER");
            entity.Property(e => e.ModifiedDate)
                .HasDefaultValueSql("datetime('now')")
                .HasColumnType("DATETIME");
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.ProductCategoryId).HasColumnName("ProductCategoryID");
            entity.Property(e => e.ProductModelId).HasColumnName("ProductModelID");
            entity.Property(e => e.ProductNumber).IsRequired();
            entity.Property(e => e.Rowguid).HasColumnName("rowguid");
            entity.Property(e => e.SellEndDate).HasColumnType("DATETIME");
            entity.Property(e => e.SellStartDate).HasColumnType("DATETIME");
            entity.Property(e => e.StandardCost).HasColumnType("INTEGER");
            entity.Property(e => e.Weight).HasColumnType("INTEGER");

            entity.HasOne(d => d.ProductModel).WithMany(p => p.Products).HasForeignKey(d => d.ProductModelId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Product> entity);
    }
}
