// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using One_P7.ThreeLayer.Database.SQLiteAdventureWorks.Models;
using System;
using System.Collections.Generic;

namespace One_P7.ThreeLayer.Database.SQLiteAdventureWorks.Models.Configurations
{
    public partial class SalesOrderHeaderConfiguration : IEntityTypeConfiguration<SalesOrderHeader>
    {
        public void Configure(EntityTypeBuilder<SalesOrderHeader> entity)
        {
            entity.HasKey(e => e.SalesOrderId);

            entity.ToTable("SalesOrderHeader");

            entity.HasIndex(e => e.Rowguid, "IX_SalesOrderHeader_rowguid").IsUnique();

            entity.HasIndex(e => e.SalesOrderNumber, "IX_SalesOrderHeader_SalesOrderNumber").IsUnique();

            entity.HasIndex(e => e.CustomerId, "IX_SalesOrderHeader_CustomerID");

            entity.Property(e => e.SalesOrderId).HasColumnName("SalesOrderID");
            entity.Property(e => e.BillToAddressId)
                .HasColumnType("INT")
                .HasColumnName("BillToAddressID");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.DueDate).HasColumnType("DATETIME");
            entity.Property(e => e.Freight).HasColumnType("INTEGER");
            entity.Property(e => e.ModifiedDate)
                .HasDefaultValueSql("datetime('now')")
                .HasColumnType("DATETIME");
            entity.Property(e => e.OnlineOrderFlag).HasDefaultValue(1);
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("datetime('now')")
                .HasColumnType("DATETIME");
            entity.Property(e => e.PurchaseOrderNumber).HasColumnType("INTEGER");
            entity.Property(e => e.Rowguid).HasColumnName("rowguid");
            entity.Property(e => e.SalesOrderNumber).IsRequired();
            entity.Property(e => e.ShipDate).HasColumnType("DATETIME");
            entity.Property(e => e.ShipMethod).IsRequired();
            entity.Property(e => e.ShipToAddressId)
                .HasColumnType("INT")
                .HasColumnName("ShipToAddressID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.SubTotal).HasColumnType("INTEGER");
            entity.Property(e => e.TaxAmt).HasColumnType("INTEGER");
            entity.Property(e => e.TotalDue).HasColumnType("INTEGER");

            entity.HasOne(d => d.BillToAddress).WithMany(p => p.SalesOrderHeaderBillToAddresses).HasForeignKey(d => d.BillToAddressId);

            entity.HasOne(d => d.Customer).WithMany(p => p.SalesOrderHeaders)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.ShipToAddress).WithMany(p => p.SalesOrderHeaderShipToAddresses).HasForeignKey(d => d.ShipToAddressId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SalesOrderHeader> entity);
    }
}
