// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace One_P7.ThreeLayer.Database.SQLiteAdventureWorks.Models;

public partial class BuildVersion
{
    public int SystemInformationId { get; set; }

    public string DatabaseVersion { get; set; }

    public DateTime VersionDate { get; set; }

    public DateTime ModifiedDate { get; set; }
}