// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace One_P7.ThreeLayer.Database.SQLiteAdventureWorks.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public int NameStyle { get; set; }

    public string Title { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Suffix { get; set; }

    public string CompanyName { get; set; }

    public string SalesPerson { get; set; }

    public string EmailAddress { get; set; }

    public string Phone { get; set; }

    public string PasswordHash { get; set; }

    public string PasswordSalt { get; set; }

    public Guid Rowguid { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; } = new List<CustomerAddress>();

    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; } = new List<SalesOrderHeader>();
}