// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace One_P7.ThreeLayer.Database.SQLiteAdventureWorks.Models;

public partial class SalesOrderHeader
{
    public int SalesOrderId { get; set; }

    public int RevisionNumber { get; set; }

    public DateTime OrderDate { get; set; }

    public DateTime DueDate { get; set; }

    public DateTime? ShipDate { get; set; }

    public int Status { get; set; }

    public int OnlineOrderFlag { get; set; }

    public string SalesOrderNumber { get; set; }

    public string PurchaseOrderNumber { get; set; }

    public string AccountNumber { get; set; }

    public int CustomerId { get; set; }

    public int? ShipToAddressId { get; set; }

    public int? BillToAddressId { get; set; }

    public string ShipMethod { get; set; }

    public string CreditCardApprovalCode { get; set; }

    public double SubTotal { get; set; }

    public double TaxAmt { get; set; }

    public double Freight { get; set; }

    public double TotalDue { get; set; }

    public string Comment { get; set; }

    public Guid Rowguid { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual Address BillToAddress { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; } = new List<SalesOrderDetail>();

    public virtual Address ShipToAddress { get; set; }
}