// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace One_P7.ThreeLayer.Database.SQLiteAdventureWorks.Models;

public partial class SalesOrderDetail
{
    public int SalesOrderId { get; set; }

    public int SalesOrderDetailId { get; set; }

    public int OrderQty { get; set; }

    public int ProductId { get; set; }

    public double UnitPrice { get; set; }

    public double UnitPriceDiscount { get; set; }

    public double LineTotal { get; set; }

    public Guid Rowguid { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }

    public virtual SalesOrderHeader SalesOrder { get; set; }
}